spring.application.name=breakpoint

server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/breakpoint
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

security.token.secret=BREAKPOINT_@1234321#

token.sonar=sqp_51fefa2edd68256b1e904ea142b1474c04b5e6e4 

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true